export const content_providers = [
  "Kingdom Educational Solutions",
  "Al Noor Learning Systems",
  "Saudi Digital Learning Initiative",
  "Al Manar Knowledge Providers",
  "Fahad EdTech Solutions",
  "Riyadh Education Consultants",
  "Future Scholars Curriculum Development",
  "Al Waha Digital Education",
  "Arabia STEM Learning",
  "Jeddah Curriculum Developers",
  "Knowledge Pathways",
  "Al Hilal Education Partners",
  "Elite Scholars Academy",
  "King Abdullah Content Providers",
  "Al Fursan Digital Learning",
  "National Center for Digital Learning",
  "Makkah Learning and Development",
  "Al Andalus Curriculum Solutions",
  "Royal Educational Resources",
  "Saudi Knowledge Solutions",
];

export const specializations= [
  "STEM",
  "Humanities",
  "Arts",
  "Physical Education",
  "Technology",
  "Islamic Studies",
  "Arabic Language",
  "Social Studies",
  "Engineering",
  "Medical Sciences",
];


export const subjects = [
  "Mathematics",
  "Science",
  "History",
  "Art",
  "Physical Education",
  "Islamic Studies",
  "Arabic Language",
  "Social Studies",
  "Information Technology",
  "Engineering",
  "Business Studies",
  "Medical Sciences",
  "Geography",
  "Physics",
  "Chemistry",
  "Biology",
  "Economics",
  "Psychology",
  "Literature",
  "Philosophy",
  "Environmental Science",
  "Law",
  "Architecture",
  "Health Sciences",
  "Design and Technology",
];

export const curriculum_types = [
  "Traditional",
  "Blended",
  "Online",
  "Competency-Based",
  "Project-Based",
  "Inquiry-Based",
  "Montessori",
  "International Baccalaureate",
  "Vocational",
  "Technical",
  "Flipped Classroom",
  "Experiential",
  "Thematic",
];

export const curriculumImprovementPlans_status = [
  "Completed",
  "In Progress",
  "Not Started",
  "Under Review",
  "Pending Approval",
  "Delayed",
  "Cancelled",
  "Partially Completed",
  "On Hold",
];

export const content_deliveryMethods = [
  "Video",
  "Interactive Modules",
  "Online Quiz",
  "Downloadable PDFs",
  "Live Webinar",
  "E-books",
  "Audio Lectures",
  "Discussion Forums",
  "Infographics",
  "Virtual Reality (VR)",
  "Augmented Reality (AR)",
  "Simulation-based Learning",
  "Gamified Learning",
  "Mobile App-based Content",
  "Podcast Episodes",
  "Social Learning Platforms",
  "Email-based Lessons",
];

export const resource_names = [
  "Algebra Workbook",
  "Science Lab Manual",
  "Historical Timeline Guide",
  "Physics Experiment Kit",
  "Art Tutorial",
  "Grammar Guidebook",
  "Math Practice Quiz",
  "Programming Guide",
  "World Geography Map",
  "Environmental Studies Journal",
  "Arabic Language Textbook",
  "Islamic Studies Reader",
  "Interactive Coding Exercise",
  "Physical Education Activity Chart",
  "Digital Photography Manual",
  "Engineering Design Blueprint",
  "Health and Nutrition Guide",
  "Ethics and Philosophy Booklet",
];

export const resource_types = [
  "Book",
  "Video",
  "Interactive Module",
  "Worksheet",
  "E-book",
  "Podcast",
  "Flashcards",
  "Presentation Slides",
  "Quiz",
  "Simulation",
  "Infographic",
  "Lab Manual",
  "Case Study",
  "Study Guide",
  "Audio Lecture",
  "Practice Exercise",
  "Mobile App",
  "Game-based Learning Resource",
];