export const firstNames = [
  "John",
  "David",
  "Michael",
  "Sarah",
  "Jessica",
  "Emily",
  "James",
  "Robert",
  "Emma",
  "Olivia",
  "William",
  "Sophia",
  "Benjamin",
  "Liam",
  "Isabella",
  "Mia",
  "Alexander",
  "Ethan",
  "Noah",
  "Mason",
  "Ava",
  "Charlotte",
  "Lucas",
  "Henry",
  "Samuel",
  "Grace",
  "Amelia",
  "Daniel",
  "Jacob",
  "Elijah",
  "Hannah",
  "Abigail",
  "Logan",
  "Madison",
  "Ella",
  "Chloe",
  "Lily",
  "Sebastian",
  "Matthew",
  "Andrew",
  "Evelyn",
  "Victoria",
  "Harper",
  "Zoey",
  "Nathan",
  "Jack",
  "Gabriel",
  "Riley",
  "Elizabeth",
  "Samantha",
];

export const lastNames = [
  "Smith",
  "Johnson",
  "Brown",
  "Taylor",
  "Anderson",
  "Walker",
  "Clark",
  "Wright",
  "Scott",
  "Lewis",
  "Thompson",
  "Martinez",
  "Robinson",
  "Lee",
  "Garcia",
  "Martinez",
  "Rodriguez",
  "Davis",
  "White",
  "Lopez",
  "Harris",
  "King",
  "Carter",
  "Mitchell",
  "Perez",
  "Green",
  "Murphy",
  "Collins",
  "Hill",
  "Sanchez",
  "Allen",
  "Hernandez",
  "Baker",
  "Nelson",
  "Hall",
  "Young",
  "Gonzalez",
  "Adams",
  "Turner",
  "Morris",
  "Campbell",
  "Parker",
  "Morgan",
  "Stewart",
  "Reed",
  "Cook",
  "Price",
  "Foster",
  "Jenkins",
  "Powell",
];

export const employmentStatuses = [
  "Active",
  "On Leave",
  "Resigned",
  "Retired",
  "Suspended",
  "Terminated",
  "Probation",
  "Training",
  "Medical Leave",
  "Temporary Assignment",
  "Internship",
  "Part-Time",
  "Full-Time",
  "Seasonal",
];

export const departments = [
  "Ground Operations",
  "Cargo",
  "Security",
  "Passenger Services",
];

export const roleDescriptions = {
  "Ground Marshaller":
    "Responsible for guiding aircraft during arrival, parking, and departure using hand signals or communication equipment.",
  "Baggage Handler":
    "Manages the loading, unloading, and transportation of passenger luggage and cargo within the airport grounds.",
  "Cargo Supervisor":
    "Oversees the handling, storage, and transport of cargo, ensuring proper documentation and compliance with safety regulations.",
  "Safety Officer":
    "Ensures that all ground operations comply with safety regulations and conducts regular safety audits and incident investigations.",
};

export const requiredCertifications = {
  "Ground Marshaller": [
    "Aircraft Marshalling Certificate",
    "Safety Procedures Training",
    "Airside Safety License",
  ],
  "Baggage Handler": [
    "Baggage Handling Safety Certificate",
    "Forklift Operation License",
    "Cargo Handling Training",
  ],
  "Cargo Supervisor": [
    "Cargo Handling Certification",
    "Dangerous Goods Awareness",
    "Safety Management Training",
  ],
  "Safety Officer": [
    "Health and Safety Certification",
    "Fire Safety Awareness",
    "Incident Investigation Training",
  ],
};


export const certificationNames = [
  "Security Clearance",
  "Equipment Operation",
  "First Aid",
  "Airside Driving",
  "Cargo Handling",
  "Fire Safety",
  "Emergency Response",
  "Ramp Safety",
  "Aircraft Marshalling",
  "Hazardous Materials Handling",
  "Forklift Operation",
  "Customs Compliance",
  "Passenger Screening",
  "Explosives Detection",
  "Ground Handling Safety",
  "Dangerous Goods Awareness",
  "Health and Safety",
  "Incident Management",
  "Radio Communication",
  "Crew Resource Management",
];

export const issuingAuthorities = [
  "Civil Aviation Authority",
  "Menzies Aviation Training Academy",
  "International Air Transport Association (IATA)",
  "UK Department for Transport",
  "National Aviation Security Committee",
  "Federal Aviation Administration (FAA)",
  "European Aviation Safety Agency (EASA)",
  "International Civil Aviation Organization (ICAO)",
  "British Red Cross",
  "National Health Service (NHS)",
  "Airport Authority",
  "Transport Security Administration (TSA)",
  "Health and Safety Executive (HSE)",
  "Civil Aviation Safety Authority (CASA)",
  "International Maritime Organization (IMO)",
  "Airports Council International (ACI)",
  "International Fire Safety Standards Coalition",
  "Occupational Safety and Health Administration (OSHA)",
  "Fire Protection Association",
  "National Safety Council",
];

export const trainingNames = [
  "Safety Training",
  "Equipment Training",
  "Security Awareness",
  "Emergency Response",
  "First Aid Training",
  "Fire Safety Training",
  "Hazardous Materials Handling",
  "Aircraft Marshalling Training",
  "Customer Service Training",
  "Cargo Handling Training",
  "Ground Operations Training",
  "Crew Resource Management Training",
  "Health and Safety Training",
  "Radio Communication Training",
  "Conflict Resolution Training",
  "Leadership and Management Training",
  "Ramp Safety Training",
  "Passenger Screening Training",
  "Explosive Detection Training",
  "Incident Management Training",
];

export const trainingProviders = [
  "Menzies Aviation Training Academy",
  "Civil Aviation Authority",
  "International Air Transport Association (IATA)",
  "British Red Cross",
  "Health and Safety Executive (HSE)",
  "Federal Aviation Administration (FAA)",
  "European Aviation Safety Agency (EASA)",
  "International Civil Aviation Organization (ICAO)",
  "National Fire Protection Association",
  "Transport Security Administration (TSA)",
  "Occupational Safety and Health Administration (OSHA)",
  "Fire Protection Association",
  "International Ground Safety Council",
  "International Civil Defense Organization",
  "Global Aviation Training Solutions",
  "Aviation Security International",
  "Aviation Leadership Institute",
  "National Safety Council",
  "International Fire Safety Standards Coalition",
  "Airports Council International (ACI)",
];

export const aircraftTypesHandled = [
  "Boeing 737",
  "Airbus A320",
  "Boeing 747",
  "Airbus A380",
  "Embraer E175",
  "Boeing 777",
  "Airbus A330",
  "Boeing 787",
  "Bombardier CRJ700",
  "Cessna 172",
  "Gulfstream G650",
  "Lockheed C-130",
  "Boeing 767",
  "Airbus A350",
  "Dassault Falcon 900",
  "Boeing 757",
  "Piper PA-28",
  "McDonnell Douglas MD-11",
  "Boeing 727",
  "Airbus A340",
];

export const baggageSystemProficiency = [
  "Conveyor Belt Systems",
  "Automated Baggage Scanning",
  "RFID Tag Systems",
  "Baggage Sorting Robotics",
  "Manual Baggage Loading",
  "Palletizing Systems",
  "Cart and Dolly Operations",
  "Baggage Weighing Systems",
  "X-Ray Baggage Inspection",
  "Cargo Hold Optimization",
  "ULD (Unit Load Device) Management",
  "Baggage Tagging Systems",
  "Automated Storage Retrieval",
  "Customs Clearance Baggage System",
  "Luggage Tracking Software",
  "Mobile Loading Platforms",
  "Overweight Luggage Handling",
  "Remote Bag Tracking",
  "Baggage Carousel Management",
  "Security-Integrated Baggage System",
];

export const cargoTypesManaged = [
  "Perishable Goods",
  "Pharmaceuticals",
  "Dangerous Goods",
  "General Cargo",
  "Oversized Cargo",
  "Live Animals",
  "Fragile Items",
  "High-Value Cargo",
  "Automotive Parts",
  "Textiles and Apparel",
  "Machinery and Equipment",
  "Electronics and IT Equipment",
  "Consumer Goods",
  "Heavy Machinery",
  "Bulk Commodities",
  "Luxury Goods",
  "Temperature-Sensitive Cargo",
  "Hazardous Materials",
  "Food and Beverage Products",
  "Medical Supplies",
];

export const equipmentTypes = [
  "Forklift",
  "Cranes",
  "Heavy Vehicles",
  "Baggage Tugs",
  "Aircraft Tow Tractors",
  "Ground Power Units (GPU)",
  "Pushback Tractors",
  "Deicing Trucks",
  "Fuel Trucks",
  "Belt Loaders",
  "Passenger Boarding Bridges",
  "Lavatory Service Vehicles",
  "Catering Trucks",
  "Air Start Units",
  "Hydraulic Lifts",
  "Aircraft Maintenance Platforms",
  "Water Service Trucks",
  "Baggage Carts",
  "Container Loaders",
  "Stair Vehicles",
];

export const trainingModules = [
  "Fire Safety and Evacuation",
  "Personal Protective Equipment (PPE)",
  "Hazardous Materials Handling",
  "Emergency Response Procedures",
  "First Aid and CPR",
  "Aircraft Marshalling Safety",
  "Ramp Safety Protocols",
  "Cargo Handling Safety",
  "Security Awareness",
  "Manual Handling and Lifting",
  "Workplace Ergonomics",
  "Radio Communication Safety",
  "Fall Protection",
  "Fueling Safety",
  "De-icing Procedures",
  "Incident Reporting",
  "Slips, Trips, and Falls",
  "Electrical Safety",
  "Lockout/Tagout Procedures",
  "Environmental Hazards and Spills",
];

export const scenarioTypesCovered = [
  "Aircraft Fire",
  "Fuel Spill Containment",
  "Passenger Evacuation",
  "Medical Emergency",
  "Active Shooter",
  "Terrorist Threat",
  "Severe Weather Response",
  "Engine Failure",
  "Runway Incursion",
  "Hazardous Materials Spill",
  "Bomb Threat",
  "Unruly Passenger",
  "Security Breach",
  "Mass Casualty Incident",
  "Aircraft Collision",
  "Power Failure",
  "Emergency Landing",
  "Wildlife Hazard",
  "Aircraft Hijacking",
  "Radiation Leak",
];

export const teamRoleAssignments = [
  "Leader",
  "Responder",
  "Observer",
  "Medical Officer",
  "Logistics Coordinator",
  "Safety Officer",
  "Communications Lead",
  "First Aider",
  "Incident Commander",
  "Support Staff",
  "Operations Officer",
];
