export const saudiFirstNames = [
  "Ahmed",
  "Mohammed",
  "Faisal",
  "Abdulrahman",
  "Yasir",
  "Ali",
  "Hassan",
  "Omar",
  "Sarah",
  "Aisha",
  "Fatima",
  "Mariam",
  "Noor",
  "Huda",
  "Reem",
  "Amani",
  "Salman",
  "Khalid",
  "Jamal",
  "Tariq",
  "Rania",
  "Layla",
  "Noura",
  "Hala",
  "Saeed",
  "Ibrahim",
  "Yusuf",
  "Zain",
  "Lina",
  "Jana",
  "Yumna",
  "Mona",
  "Bilal",
  "Adnan",
  "Mustafa",
  "Rashid",
  "Hisham",
  "Sultan",
  "Waleed",
  "Khadija",
  "Nadine",
  "Samar",
  "Zahra",
  "Ruqayya",
  "Lubna",
  "Maha",
  "Basma",
  "Joud",
];

export const saudiLastNames = [
  "Al-Farsi",
  "Al-Harbi",
  "Al-Saud",
  "Al-Shammari",
  "Al-Mutairi",
  "Al-Qurashi",
  "Al-Mansour",
  "Al-Jaber",
  "Al-Rashid",
  "Al-Zahrani",
  "Al-Dosari",
  "Al-Hussain",
  "Al-Salem",
  "Al-Johani",
  "Al-Omari",
  "Al-Ahmad",
  "Al-Sheikh",
  "Al-Khalifa",
  "Al-Ali",
  "Al-Mujahid",
  "Al-Qadi",
  "Al-Hariri",
  "Al-Jamal",
  "Al-Farhan",
  "Al-Nasser",
  "Al-Sabah",
  "Al-Mufeed",
  "Al-Baz",
  "Al-Rawi",
  "Al-Mutlaq",
  "Al-Habib",
  "Al-Najjar",
  "Al-Muhanna",
  "Al-Sabti",
  "Al-Karim",
  "Al-Ghamdi",
];

export  const gradeLevels = [
  { level: "Kindergarten", minAge: 4, maxAge: 5 },
  { level: "Grade 1", minAge: 5, maxAge: 6 },
  { level: "Grade 2", minAge: 6, maxAge: 7 },
  { level: "Grade 3", minAge: 7, maxAge: 8 },
  { level: "Grade 4", minAge: 8, maxAge: 9 },
  { level: "Grade 5", minAge: 9, maxAge: 10 },
  { level: "Grade 6", minAge: 10, maxAge: 11 },
  { level: "Grade 7", minAge: 11, maxAge: 12 },
  { level: "Grade 8", minAge: 12, maxAge: 13 },
  { level: "Grade 9", minAge: 13, maxAge: 14 },
  { level: "Grade 10", minAge: 14, maxAge: 15 },
  { level: "Grade 11", minAge: 15, maxAge: 16 },
  { level: "Grade 12", minAge: 16, maxAge: 17 },
  { level: "Undergraduate Year 1", minAge: 18, maxAge: 19 },
  { level: "Undergraduate Year 2", minAge: 19, maxAge: 20 },
  { level: "Undergraduate Year 3", minAge: 20, maxAge: 21 },
  { level: "Undergraduate Year 4", minAge: 21, maxAge: 22 },
  { level: "Postgraduate", minAge: 22, maxAge: 25 },
];


export const device_types = [
  "Laptop",
  "Tablet",
  "Smartphone",
  "Desktop",
  "Smartwatch",
  "E-reader",
  "Gaming Console",
  "VR Headset",
  "Smart TV",
];

export const engagement_levels = [
  "Very Low",
  "Low",
  "Moderate",
  "Above Average",
  "High",
  "Very High",
  "Exceptional",
];