export const districtsDataset = [
  {
    district: "Ahmedabad",
    population: 7045313,
    latestPopulation: 7214225,
    percentageChangeFromLastCensus: "11.45",
    gdpPerCapitaPerPersonPerYear: "4.04",
    gdpAmountIn2019InCrores: 284630,
    gdpAmountIn2023InCrores: 450893,
    targetGDPIn2030InCrores: 1668306,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Surat",
    population: 6079231,
    latestPopulation: 6081322,
    percentageChangeFromLastCensus: "9.88",
    gdpPerCapitaPerPersonPerYear: "2.51",
    gdpAmountIn2019InCrores: 152588,
    gdpAmountIn2023InCrores: 241721,
    targetGDPIn2030InCrores: 894368,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Vadodara",
    population: 4193795,
    latestPopulation: 4165626,
    percentageChangeFromLastCensus: "6.82",
    gdpPerCapitaPerPersonPerYear: "3.03",
    gdpAmountIn2019InCrores: 127071,
    gdpAmountIn2023InCrores: 201299,
    targetGDPIn2030InCrores: 744807,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Banaskantha",
    population: 3116045,
    latestPopulation: 3120506,
    percentageChangeFromLastCensus: "5.07",
    gdpPerCapitaPerPersonPerYear: "1.45",
    gdpAmountIn2019InCrores: 45182,
    gdpAmountIn2023InCrores: 71575,
    targetGDPIn2030InCrores: 264829,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Rajkot",
    population: 3015229,
    latestPopulation: 3804558,
    percentageChangeFromLastCensus: "4.90",
    gdpPerCapitaPerPersonPerYear: "2.46",
    gdpAmountIn2019InCrores: 74174,
    gdpAmountIn2023InCrores: 117502,
    targetGDPIn2030InCrores: 434759,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Bhavnagar",
    population: 2393272,
    latestPopulation: 2880365,
    percentageChangeFromLastCensus: "3.89",
    gdpPerCapitaPerPersonPerYear: "1.67",
    gdpAmountIn2019InCrores: 39967,
    gdpAmountIn2023InCrores: 63314,
    targetGDPIn2030InCrores: 234262,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Dahod",
    population: 2126558,
    latestPopulation: 2200073,
    percentageChangeFromLastCensus: "3.46",
    gdpPerCapitaPerPersonPerYear: "0.87",
    gdpAmountIn2019InCrores: 18590,
    gdpAmountIn2023InCrores: 29449,
    targetGDPIn2030InCrores: 108963,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Kheda",
    population: 2090313,
    latestPopulation: 2299885,
    percentageChangeFromLastCensus: "3.40",
    gdpPerCapitaPerPersonPerYear: "1.41",
    gdpAmountIn2019InCrores: 29473,
    gdpAmountIn2023InCrores: 46689,
    targetGDPIn2030InCrores: 172752,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Anand",
    population: 2090276,
    latestPopulation: 2092745,
    percentageChangeFromLastCensus: "3.40",
    gdpPerCapitaPerPersonPerYear: "1.41",
    gdpAmountIn2019InCrores: 29472,
    gdpAmountIn2023InCrores: 46689,
    targetGDPIn2030InCrores: 172749,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Kutch",
    population: 2053769,
    latestPopulation: 2122337,
    percentageChangeFromLastCensus: "3.34",
    gdpPerCapitaPerPersonPerYear: "2.64",
    gdpAmountIn2019InCrores: 54219,
    gdpAmountIn2023InCrores: 85891,
    targetGDPIn2030InCrores: 317796,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Mehsana",
    population: 2027727,
    latestPopulation: 2094567,
    percentageChangeFromLastCensus: "3.30",
    gdpPerCapitaPerPersonPerYear: "2.31",
    gdpAmountIn2019InCrores: 46840,
    gdpAmountIn2023InCrores: 74201,
    targetGDPIn2030InCrores: 274546,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Valsad",
    population: 1705678,
    latestPopulation: 1705678,
    percentageChangeFromLastCensus: "2.77",
    gdpPerCapitaPerPersonPerYear: "1.67",
    gdpAmountIn2019InCrores: 28484,
    gdpAmountIn2023InCrores: 45123,
    targetGDPIn2030InCrores: 166958,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Panchmahal",
    population: 1642268,
    latestPopulation: 2390776,
    percentageChangeFromLastCensus: "2.67",
    gdpPerCapitaPerPersonPerYear: "0.87",
    gdpAmountIn2019InCrores: 14356,
    gdpAmountIn2023InCrores: 22742,
    targetGDPIn2030InCrores: 84148,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Surendranagar",
    population: 1585268,
    latestPopulation: 1756268,
    percentageChangeFromLastCensus: "2.58",
    gdpPerCapitaPerPersonPerYear: "1.90",
    gdpAmountIn2019InCrores: 30120,
    gdpAmountIn2023InCrores: 47714,
    targetGDPIn2030InCrores: 176542,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Bharuch",
    population: 1550822,
    latestPopulation: 1551019,
    percentageChangeFromLastCensus: "2.52",
    gdpPerCapitaPerPersonPerYear: "3.32",
    gdpAmountIn2019InCrores: 51487,
    gdpAmountIn2023InCrores: 81562,
    targetGDPIn2030InCrores: 301782,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Junagadh",
    population: 1525605,
    latestPopulation: 2743082,
    percentageChangeFromLastCensus: "2.48",
    gdpPerCapitaPerPersonPerYear: "1.34",
    gdpAmountIn2019InCrores: 20443,
    gdpAmountIn2023InCrores: 32384,
    targetGDPIn2030InCrores: 119823,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Amreli",
    population: 1513614,
    latestPopulation: 1514190,
    percentageChangeFromLastCensus: "2.46",
    gdpPerCapitaPerPersonPerYear: "1.53",
    gdpAmountIn2019InCrores: 23158,
    gdpAmountIn2023InCrores: 36685,
    targetGDPIn2030InCrores: 135737,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Jamnagar",
    population: 1407635,
    latestPopulation: 2160119,
    percentageChangeFromLastCensus: "2.29",
    gdpPerCapitaPerPersonPerYear: "2.88",
    gdpAmountIn2019InCrores: 40539,
    gdpAmountIn2023InCrores: 64220,
    targetGDPIn2030InCrores: 237616,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Sabarkantha",
    population: 1388671,
    latestPopulation: 2428589,
    percentageChangeFromLastCensus: "2.26",
    gdpPerCapitaPerPersonPerYear: "1.64",
    gdpAmountIn2019InCrores: 22774,
    gdpAmountIn2023InCrores: 36077,
    targetGDPIn2030InCrores: 133486,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Gandhinagar",
    population: 1387478,
    latestPopulation: 1391753,
    percentageChangeFromLastCensus: "2.26",
    gdpPerCapitaPerPersonPerYear: "3.72",
    gdpAmountIn2019InCrores: 51614,
    gdpAmountIn2023InCrores: 81763,
    targetGDPIn2030InCrores: 302526,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Patan",
    population: 1342746,
    latestPopulation: 1343734,
    percentageChangeFromLastCensus: "2.18",
    gdpPerCapitaPerPersonPerYear: "1.86",
    gdpAmountIn2019InCrores: 24975,
    gdpAmountIn2023InCrores: 39563,
    targetGDPIn2030InCrores: 146386,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Navsari",
    population: 1330711,
    latestPopulation: 1329672,
    percentageChangeFromLastCensus: "2.16",
    gdpPerCapitaPerPersonPerYear: "2.16",
    gdpAmountIn2019InCrores: 28743,
    gdpAmountIn2023InCrores: 45533,
    targetGDPIn2030InCrores: 168473,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Gir Somnath",
    population: 1217477,
    latestPopulation: 1241572,
    percentageChangeFromLastCensus: "1.98",
    gdpPerCapitaPerPersonPerYear: "1.34",
    gdpAmountIn2019InCrores: 16314,
    gdpAmountIn2023InCrores: 25843,
    targetGDPIn2030InCrores: 95622,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Chhota Udaipur",
    population: 1071831,
    latestPopulation: 1090506,
    percentageChangeFromLastCensus: "1.74",
    gdpPerCapitaPerPersonPerYear: "3.03",
    gdpAmountIn2019InCrores: 32476,
    gdpAmountIn2023InCrores: 51447,
    targetGDPIn2030InCrores: 190354,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Aravalli",
    population: 1039918,
    latestPopulation: 1057498,
    percentageChangeFromLastCensus: "1.69",
    gdpPerCapitaPerPersonPerYear: "1.64",
    gdpAmountIn2019InCrores: 17054,
    gdpAmountIn2023InCrores: 27016,
    targetGDPIn2030InCrores: 99962,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Mahisagar",
    population: 994624,
    latestPopulation: 1010706,
    percentageChangeFromLastCensus: "1.62",
    gdpPerCapitaPerPersonPerYear: "1.02",
    gdpAmountIn2019InCrores: 10145,
    gdpAmountIn2023InCrores: 16071,
    targetGDPIn2030InCrores: 59463,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Morbi",
    population: 960329,
    latestPopulation: 975321,
    percentageChangeFromLastCensus: "1.56",
    gdpPerCapitaPerPersonPerYear: "2.40",
    gdpAmountIn2019InCrores: 23047,
    gdpAmountIn2023InCrores: 36510,
    targetGDPIn2030InCrores: 135090,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Tapi",
    population: 806489,
    latestPopulation: 807022,
    percentageChangeFromLastCensus: "1.31",
    gdpPerCapitaPerPersonPerYear: "2.51",
    gdpAmountIn2019InCrores: 20242,
    gdpAmountIn2023InCrores: 32067,
    targetGDPIn2030InCrores: 118649,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
  {
    district: "Devbhumi Dwarka",
    population: 752484,
    latestPopulation: 761688,
    percentageChangeFromLastCensus: "1.22",
    gdpPerCapitaPerPersonPerYear: "2.88",
    gdpAmountIn2019InCrores: 21671,
    gdpAmountIn2023InCrores: 34330,
    targetGDPIn2030InCrores: 127023,
    agricultureRevenueInCrores: 15109,
    agricultureAllocationInCrores: 5875,
    educationAndDevelopmentRevenueInCrores: 16788,
    educationAndDevelopmentAllocationInCrores: 7554,
    healthAndFamilyWelfareRevenueInCrores: 11751,
    healthAndFamilyWelfareAllocationInCrores: 5036,
    tourismRevenueInCrores: 5875,
    tourismAllocationInCrores: 1678,
    commerceAndIndustryRevenueInCrores: 21824,
    commerceAndIndustryAllocationInCrores: 9233,
    governmentSchemes:
      "Soil Health Card, PM Kaushal Vikas Yojana, Sukanya Samriddhi Yojana, Smart Cities Mission",
  },
  {
    district: "Botad",
    population: 656005,
    latestPopulation: 663000,
    percentageChangeFromLastCensus: "1.07",
    gdpPerCapitaPerPersonPerYear: "2.79",
    gdpAmountIn2019InCrores: 18302,
    gdpAmountIn2023InCrores: 28993,
    targetGDPIn2030InCrores: 107276,
    agricultureRevenueInCrores: 16788,
    agricultureAllocationInCrores: 6715,
    educationAndDevelopmentRevenueInCrores: 21824,
    educationAndDevelopmentAllocationInCrores: 8394,
    healthAndFamilyWelfareRevenueInCrores: 15109,
    healthAndFamilyWelfareAllocationInCrores: 5875,
    tourismRevenueInCrores: 6715,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 25182,
    commerceAndIndustryAllocationInCrores: 10912,
    governmentSchemes: "E-NAM, Stand-up India, PM Gramin Awaas Yojana, AMRUT",
  },
  {
    district: "Narmada",
    population: 590379,
    latestPopulation: 590297,
    percentageChangeFromLastCensus: "0.96",
    gdpPerCapitaPerPersonPerYear: "3.12",
    gdpAmountIn2019InCrores: 18419,
    gdpAmountIn2023InCrores: 29179,
    targetGDPIn2030InCrores: 107964,
    agricultureRevenueInCrores: 29378,
    agricultureAllocationInCrores: 10072,
    educationAndDevelopmentRevenueInCrores: 34415,
    educationAndDevelopmentAllocationInCrores: 12591,
    healthAndFamilyWelfareRevenueInCrores: 21824,
    healthAndFamilyWelfareAllocationInCrores: 8394,
    tourismRevenueInCrores: 10072,
    tourismAllocationInCrores: 4197,
    commerceAndIndustryRevenueInCrores: 43648,
    commerceAndIndustryAllocationInCrores: 16788,
    governmentSchemes:
      "Krishi Bhagya, Skill India, Ayushman Bharat, Pradhan Mantri Awas Yojana",
  },
  {
    district: "Porbandar",
    population: 586062,
    latestPopulation: 585449,
    percentageChangeFromLastCensus: "0.95",
    gdpPerCapitaPerPersonPerYear: "1.34",
    gdpAmountIn2019InCrores: 7853,
    gdpAmountIn2023InCrores: 12440,
    targetGDPIn2030InCrores: 46030,
    agricultureRevenueInCrores: 24342,
    agricultureAllocationInCrores: 9233,
    educationAndDevelopmentRevenueInCrores: 29378,
    educationAndDevelopmentAllocationInCrores: 11751,
    healthAndFamilyWelfareRevenueInCrores: 19306,
    healthAndFamilyWelfareAllocationInCrores: 7554,
    tourismRevenueInCrores: 8394,
    tourismAllocationInCrores: 3357,
    commerceAndIndustryRevenueInCrores: 40291,
    commerceAndIndustryAllocationInCrores: 15948,
    governmentSchemes:
      "MGNREGA, Start-up India, PM Jan Dhan Yojana, Swachh Bharat Abhiyan",
  },
  {
    district: "Dang",
    population: 226769,
    latestPopulation: 227604,
    percentageChangeFromLastCensus: "0.37",
    gdpPerCapitaPerPersonPerYear: "1.53",
    gdpAmountIn2019InCrores: 3469,
    gdpAmountIn2023InCrores: 5496,
    targetGDPIn2030InCrores: 20336,
    agricultureRevenueInCrores: 19306,
    agricultureAllocationInCrores: 7554,
    educationAndDevelopmentRevenueInCrores: 23503,
    educationAndDevelopmentAllocationInCrores: 10072,
    healthAndFamilyWelfareRevenueInCrores: 15948,
    healthAndFamilyWelfareAllocationInCrores: 6715,
    tourismRevenueInCrores: 7554,
    tourismAllocationInCrores: 2518,
    commerceAndIndustryRevenueInCrores: 31057,
    commerceAndIndustryAllocationInCrores: 13430,
    governmentSchemes:
      "PM Fasal Bima Yojana, Digital India, Pradhan Mantri Ujjwala Yojana, Make in India",
  },
];


export const govtSchemesData = [
  {
    SchemeName: "MGNREGA",
    SchemeDescription:
      "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA) aims to enhance the livelihood security of people in rural areas by guaranteeing 100 days of wage employment in a financial year to a rural household.",
  },
  {
    SchemeName: "Start-up India",
    SchemeDescription:
      "Start-up India is a government initiative to foster innovation, promote entrepreneurship, and help startups grow through a range of support measures including tax exemptions, funding support, and mentorship.",
  },
  {
    SchemeName: "PM Jan Dhan Yojana",
    SchemeDescription:
      "Pradhan Mantri Jan Dhan Yojana (PMJDY) is a financial inclusion program that aims to ensure access to financial services such as banking accounts, remittances, credit, insurance, and pensions for weaker sections of society.",
  },
  {
    SchemeName: "Swachh Bharat Abhiyan",
    SchemeDescription:
      "Swachh Bharat Abhiyan is a nation-wide campaign to clean up the streets, roads, and infrastructure of India's cities and rural areas, focusing on sanitation and hygiene.",
  },
  {
    SchemeName: "Ayushman Bharat",
    SchemeDescription:
      "Ayushman Bharat is a healthcare initiative aimed at providing health cover to economically vulnerable families, offering up to ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
  },
  {
    SchemeName: "Krishi Bhagya",
    SchemeDescription:
      "Krishi Bhagya is a scheme aimed at boosting agriculture productivity in Karnataka by improving irrigation facilities, promoting sustainable farming, and enhancing farmers' incomes.",
  },
  {
    SchemeName: "Skill India",
    SchemeDescription:
      "Skill India is a government campaign to provide vocational training and skill development to the youth of India, aiming to make them employable in various industries.",
  },
  {
    SchemeName: "Pradhan Mantri Awas Yojana",
    SchemeDescription:
      "Pradhan Mantri Awas Yojana (PMAY) is a housing scheme that aims to provide affordable housing to all by 2022, with a focus on economically weaker sections and low-income groups.",
  },
  {
    SchemeName: "E-NAM",
    SchemeDescription:
      "National Agriculture Market (E-NAM) is an online trading platform for agricultural commodities in India, aimed at providing better market access for farmers and improving price realization.",
  },
  {
    SchemeName: "Stand-up India",
    SchemeDescription:
      "Stand-up India provides loans to SC/ST and women entrepreneurs to promote entrepreneurship among underserved segments and to support greenfield enterprises.",
  },
  {
    SchemeName: "PM Fasal Bima Yojana",
    SchemeDescription:
      "Pradhan Mantri Fasal Bima Yojana (PMFBY) is a crop insurance scheme that provides financial support to farmers suffering crop loss or damage due to natural calamities.",
  },
  {
    SchemeName: "Digital India",
    SchemeDescription:
      "Digital India is a campaign to ensure that government services are made available to citizens electronically, by improving online infrastructure and increasing Internet connectivity.",
  },
  {
    SchemeName: "PM Ujjwala Yojana",
    SchemeDescription:
      "Pradhan Mantri Ujjwala Yojana (PMUY) aims to provide LPG connections to women from below-poverty-line households, reducing health risks associated with traditional cooking fuels.",
  },
  {
    SchemeName: "Make in India",
    SchemeDescription:
      "Make in India is an initiative to encourage national and multinational companies to manufacture their products in India and to promote India as a global manufacturing hub.",
  },
  {
    SchemeName: "Soil Health Card",
    SchemeDescription:
      "The Soil Health Card Scheme aims to issue soil health cards to farmers, providing them with information about the nutrient status of their soil and recommendations for improving soil health.",
  },
  {
    SchemeName: "Smart Cities Mission",
    SchemeDescription:
      "Smart Cities Mission is an urban renewal and retrofitting program to make cities sustainable and citizen-friendly, focusing on smart infrastructure, efficient resource management, and governance.",
  },
];

