export const purgeNames = {
  AROUND: "AROUND",
  IZAK: "IZAK",
  AEGIS: "AEGIS",
  AEGISAPPDATA: "AEGISAPPDATA",
  AROUNDAPPDATA: "AROUNDAPPDATA",
  NOORSYSTEMSDATA: "NOORSYSTEMSDATA",
  VISION2030: "VISION2030",
  // AROUNDAPPDATA: "AROUNDAPPDATA",
  TATWEERPROGRAM: "TATWEERPROGRAM",
  MOE: "MOEDATA",
  SCHOOLPROGRAM: "SCHOOLPROGRAM",
  CONTENTPROVIDER: "CONTENTPROVIDER",
  STUDENTDATA: "STUDENTDATA",
};


