export const tatweerProgram = {
  tatweerProgram: [
    {
      program_name: "Digital Literacy Enhancement",
      goals: "Improve digital literacy across all student levels.",
      key_challenges:
        "Limited access to digital devices, Low internet connectivity in rural areas.",
    },
    {
      program_name: "STEM Integration in Curriculum",
      goals: "Integrate STEM subjects into the national curriculum.",
      key_challenges:
        "Lack of trained STEM teachers, Resistance to new teaching methodologies.",
    },
    {
      program_name: "Teacher Upskilling Initiative",
      goals: "Upskill teachers to use modern educational tools effectively.",
      key_challenges:
        "Teacher availability for training sessions, Limited budget for extensive training programs.",
    },
    {
      program_name: "Smart Classrooms Deployment",
      goals:
        "Deploy smart classrooms equipped with digital boards and interactive tools.",
      key_challenges:
        "High initial setup costs, Need for technical support and maintenance.",
    },
    {
      program_name: "Rural Education Outreach",
      goals: "Provide access to quality education in rural areas.",
      key_challenges:
        "Logistical difficulties in remote locations, Language barriers.",
    },
    {
      program_name: "E-Learning Platform Development",
      goals: "Create an e-learning platform to support remote education.",
      key_challenges:
        "Ensuring platform scalability, Ensuring data security and privacy.",
    },
    {
      program_name: "Inclusivity in Education",
      goals: "Promote inclusive education for students with disabilities.",
      key_challenges:
        "Lack of specialized training for teachers, Insufficient infrastructure adjustments.",
    },
    {
      program_name: "Parent-Teacher Engagement Program",
      goals:
        "Increase engagement between parents and teachers for student development.",
      key_challenges:
        "Scheduling conflicts, Varied levels of parental involvement.",
    },
    {
      program_name: "Blended Learning Model Implementation",
      goals:
        "Implement a blended learning model combining online and offline learning.",
      key_challenges:
        "Digital divide among students, Resistance to adopting new methods.",
    },
    {
      program_name: "Cybersecurity Awareness for Students",
      goals: "Raise awareness about cybersecurity among students.",
      key_challenges:
        "Lack of interest in cybersecurity topics, Rapid evolution of cyber threats.",
    },
    {
      program_name: "Data-Driven Decision Making in Schools",
      goals:
        "Encourage data-driven decision-making processes in educational institutions.",
      key_challenges:
        "Lack of data analytics skills among staff, Data privacy concerns.",
    },
    {
      program_name: "Science Labs Modernization",
      goals:
        "Modernize science labs in schools with state-of-the-art equipment.",
      key_challenges:
        "High costs of modern equipment, Maintenance and safety concerns.",
    },
    {
      program_name: "Reading and Comprehension Program",
      goals: "Improve reading and comprehension skills among primary students.",
      key_challenges:
        "Limited access to diverse reading materials, Low student engagement.",
    },
    {
      program_name: "AI in Education Pilot Program",
      goals: "Introduce AI tools to personalize student learning experiences.",
      key_challenges:
        "High initial investment, Need for continuous updates to AI models.",
    },
    {
      program_name: "School Health and Safety Program",
      goals: "Ensure health and safety standards in schools.",
      key_challenges:
        "Varying standards across regions, Inadequate resources for all schools.",
    },
    {
      program_name: "Advanced Mathematics Training",
      goals: "Provide advanced mathematics training to high school students.",
      key_challenges:
        "Finding qualified trainers, Student anxiety towards complex math topics.",
    },
    {
      program_name: "Teacher Mentorship Program",
      goals: "Mentor new teachers through experienced educators.",
      key_challenges:
        "Mismatch in teaching styles, Limited availability of senior teachers.",
    },
    {
      program_name: "Interactive History Learning",
      goals:
        "Make history education interactive using digital tools and simulations.",
      key_challenges:
        "High costs of developing interactive content, Technical issues with digital tools.",
    },
    {
      program_name: "Language Proficiency Improvement",
      goals: "Improve language proficiency among non-native speakers.",
      key_challenges:
        "Limited access to native-speaking teachers, Cultural differences.",
    },
    {
      program_name: "Coding for Kids",
      goals:
        "Introduce coding from an early age to foster problem-solving skills.",
      key_challenges:
        "Lack of trained instructors, High costs of software tools.",
    },
    {
      program_name: "Digital Resource Accessibility",
      goals:
        "Ensure all digital educational resources are accessible to everyone.",
      key_challenges:
        "Inadequate infrastructure in rural areas, High costs of adaptive technologies.",
    },
    {
      program_name: "Leadership Training for School Heads",
      goals: "Train school heads in leadership and management skills.",
      key_challenges:
        "Balancing training with school responsibilities, Limited budget for such programs.",
    },
    {
      program_name: "Green School Initiative",
      goals: "Promote environmental sustainability in schools.",
      key_challenges:
        "Resistance to behavioral change, Costs of green infrastructure.",
    },
    {
      program_name: "Social Emotional Learning (SEL) Program",
      goals:
        "Implement SEL curriculum across schools to improve student well-being.",
      key_challenges: "Lack of trained counselors, Diverse student needs.",
    },
    {
      program_name: "Continuous Professional Development",
      goals: "Ensure continuous professional development for educators.",
      key_challenges: "Time constraints, Budget limitations.",
    },
    {
      program_name: "Hybrid Learning Support",
      goals: "Support hybrid learning models in schools.",
      key_challenges:
        "Inconsistent internet access, Varying levels of digital literacy.",
    },
    {
      program_name: "Student Exchange Program",
      goals: "Facilitate cultural exchange programs for students.",
      key_challenges: "High travel costs, Visa and regulatory restrictions.",
    },
    {
      program_name: "Digital Content Creation",
      goals:
        "Encourage teachers to create digital content for better learning experiences.",
      key_challenges: "Technical skills gap, Time constraints.",
    },
    {
      program_name: "Innovative Learning Spaces",
      goals: "Develop innovative learning spaces to stimulate creativity.",
      key_challenges:
        "High construction costs, Limited space in urban schools.",
    },
    {
      program_name: "High School Career Guidance Program",
      goals: "Provide career guidance to high school students.",
      key_challenges:
        "Lack of trained career counselors, Diverse student interests.",
    },
    {
      program_name: "Nutrition and Wellness Program",
      goals: "Promote nutrition and wellness among students.",
      key_challenges:
        "Limited awareness, Budget constraints for healthy meals.",
    },
    {
      program_name: "Virtual Reality Learning",
      goals: "Use virtual reality to enhance learning experiences.",
      key_challenges: "High costs of VR equipment, Need for tech support.",
    },
    {
      program_name: "School Safety and Disaster Management",
      goals: "Prepare schools for natural and man-made disasters.",
      key_challenges: "Lack of emergency protocols, Limited training programs.",
    },
    {
      program_name: "Public-Private Partnership in Education",
      goals:
        "Establish partnerships with private entities to enhance education quality.",
      key_challenges:
        "Aligning goals between public and private sectors, Varying levels of commitment.",
    },
    {
      program_name: "Open Educational Resources (OER) Initiative",
      goals: "Promote the use of OER to reduce textbook costs.",
      key_challenges:
        "Quality control of open resources, Lack of awareness among educators.",
    },
    {
      program_name: "Digital Citizenship and Ethics",
      goals: "Teach students digital ethics and responsible online behavior.",
      key_challenges:
        "Ensuring engagement, Rapid changes in technology and ethics.",
    },
    {
      program_name: "Art and Culture Promotion Program",
      goals: "Integrate arts and culture into mainstream education.",
      key_challenges:
        "Balancing academic and extracurricular activities, Varying levels of interest.",
    },
    {
      program_name: "Health Education Curriculum",
      goals: "Implement a comprehensive health education curriculum.",
      key_challenges:
        "Lack of qualified health educators, Cultural sensitivities.",
    },
    {
      program_name: "Cloud-Based Learning Management System",
      goals: "Develop a cloud-based LMS for schools and colleges.",
      key_challenges:
        "Ensuring data security, High setup and maintenance costs.",
    },
    {
      program_name: "Mobile Learning Initiatives",
      goals: "Enable learning through mobile devices for flexibility.",
      key_challenges:
        "Device compatibility issues, High data costs for students.",
    },
    {
      program_name: "Financial Literacy Education",
      goals: "Introduce financial literacy as part of the curriculum.",
      key_challenges:
        "Lack of suitable educational materials, Resistance from traditional curriculum.",
    },
    {
      program_name: "Artificial Intelligence in Classrooms",
      goals: "Use AI to tailor learning experiences and support teachers.",
      key_challenges:
        "High development costs, Ethical concerns regarding AI in education.",
    },
    {
      program_name: "21st Century Skills Program",
      goals:
        "Develop skills like critical thinking, creativity, and collaboration.",
      key_challenges:
        "Lack of suitable evaluation metrics, Resistance to new teaching styles.",
    },
    {
      program_name: "School Infrastructure Development",
      goals: "Upgrade school infrastructure to meet modern standards.",
      key_challenges: "High capital expenditure, Varying regional needs.",
    },
    {
      program_name: "Mathematics Enrichment Program",
      goals:
        "Enhance math learning through interactive and practical approaches.",
      key_challenges:
        "Math anxiety among students, Lack of engaging resources.",
    },
    {
      program_name: "Digital Attendance and Record Management",
      goals: "Implement digital systems for attendance and student records.",
      key_challenges: "Data privacy concerns, High initial investment.",
    },
    {
      program_name: "Vocational Training Program",
      goals: "Expand vocational training opportunities for students.",
      key_challenges:
        "Limited access to vocational facilities, Low student enrollment.",
    },
    {
      program_name: "Educational Research and Development",
      goals: "Promote R&D in innovative teaching and learning methods.",
      key_challenges:
        "Limited funding for educational research, Time constraints for educators.",
    },
    {
      program_name: "Critical Thinking and Problem-Solving Workshops",
      goals:
        "Conduct workshops to develop critical thinking and problem-solving skills.",
      key_challenges:
        "Diverse student learning capabilities, Limited skilled trainers.",
    },
    {
      program_name: "Student Health and Mental Wellness Program",
      goals: "Provide mental health support and wellness resources.",
      key_challenges:
        "Stigma around mental health, Limited access to trained counselors.",
    },
    {
      program_name: "Interdisciplinary Learning Program",
      goals: "Promote interdisciplinary studies combining arts and sciences.",
      key_challenges:
        "Traditional mindset towards subject separation, Lack of interdisciplinary resources.",
    },
    {
      program_name: "Foreign Language Proficiency Program",
      goals:
        "Introduce foreign language learning for cultural and economic advantage.",
      key_challenges:
        "Lack of qualified language teachers, Diverse language preferences.",
    },
    {
      program_name: "Gender Equality in Education",
      goals: "Promote gender equality and awareness in education.",
      key_challenges:
        "Cultural resistance, Lack of awareness among communities.",
    },
    {
      program_name: "Heritage and History Preservation Program",
      goals: "Integrate heritage preservation in history education.",
      key_challenges:
        "Limited resources for field trips and practical learning, Varying regional interests.",
    },
    {
      program_name: "Learning Analytics in Schools",
      goals: "Implement learning analytics to enhance student outcomes.",
      key_challenges:
        "Data privacy and ethical concerns, Lack of analytics skills among educators.",
    },
    {
      program_name: "Entrepreneurship in Schools",
      goals: "Foster entrepreneurship and innovation among students.",
      key_challenges:
        "Lack of entrepreneurial mindset, Limited access to mentors and resources.",
    },
  ],
  smartClassrooms: [
    "Interactive Whiteboard",
    "Digital Projector",
    "Document Camera",
    "Classroom Response Systems",
    "Interactive Flat Panel Display",
    "3D Printer",
    "Virtual Reality Headsets",
    "Augmented Reality Devices",
    "Tablets",
    "Laptops",
    "Desktop Computers",
    "Wireless Display Adapters",
    "Smart Speakers",
    "Robotics Kits",
    "Wireless Microphones",
    "Voice Amplifiers",
    "Wearable Devices",
    "Smart Desks",
    "Digital Textbooks",
    "Online Assessment Tools",
    "E-Readers",
    "Learning Management Systems",
    "Cloud-based Collaboration Tools",
    "Digital Science Lab Equipment",
    "AI-Powered Learning Tools",
    "IoT Sensors",
    "Interactive Software Applications",
    "Digital Bulletin Boards",
    "Video Conferencing Tools",
    "Language Translation Devices",
    "Smart Lighting Systems",
    "Digital Signage",
    "Interactive Learning Stations",
    "Real-time Feedback Systems",
    "Classroom Management Software",
    "Voice Recognition Systems",
    "Gamified Learning Platforms",
    "3D Scanning Devices",
    "Smart Boards",
    "Speech-to-Text Tools",
    "Advanced Scientific Calculators",
    "Coding and Programming Kits",
    "Online Coding Platforms",
    "AI Tutors",
    "Automated Attendance Systems",
    "Student Tracking Devices",
    "Digital Arts and Music Tools",
    "Gesture-based Learning Tools",
    "Motion Sensors",
    "Voice-Activated Devices",
    "Interactive Maps and Globes",
    "Math Manipulatives Software",
    "Collaborative Whiteboarding Tools",
    "Educational Robotics",
    "Mind Mapping Tools",
    "Adaptive Learning Platforms",
    "Augmented Learning Apps",
    "Online Safety Tools",
    "Data Visualization Tools",
    "3D Modeling Software",
    "Computer-Aided Design (CAD) Tools",
    "Online Research Databases",
    "Podcasting Tools",
    "Smart Planners",
    "Virtual Dissection Kits",
    "Biometric Devices",
    "Digital Music Instruments",
    "Smart HVAC Controls",
    "Remote Learning Platforms",
    "Data Analytics Tools",
    "Interactive Quizzes",
    "Wearable Health Monitors",
    "Eye-Tracking Devices",
    "Voice Response Systems",
    "Digital Polling Tools",
    "Behavior Monitoring Systems",
    "Remote Monitoring Tools",
    "Virtual Labs",
    "Collaboration Boards",
    "Classroom Podcasting Kits",
    "Smart Glasses",
    "Screen Recording Tools",
    "Learning Analytics Dashboards",
    "Virtual Field Trip Platforms",
    "Educational Social Media Tools",
    "Screen Mirroring Tools",
    "Learning Pathways Software",
    "Smart Classroom Furniture",
    "Multimedia Projectors",
    "Digital Whiteboard Software",
    "Remote Desktop Tools",
    "Classroom IoT Hubs",
    "Interactive Reading Apps",
    "Geography Simulation Tools",
    "Mathematics Simulation Software",
    "Physics Simulation Tools",
    "Chemistry Experiment Simulators",
    "Interactive E-books",
    "Mobile Learning Applications",
    "Lecture Capture Systems",
    "Real-time Translation Tools",
    "Collaborative Document Editing Tools",
    "Holographic Projectors",
  ],
  technologyRiskIndicators: ["High", "Medium", "Low"],
  trainingRiskIndicators: ["High", "Medium", "Low"],
  deviceUsageMetrics: [
    "Interactive Whiteboard",
    "Digital Projector",
    "Document Camera",
    "3D Printer",
    "Laptop",
    "Desktop Computer",
    "Tablet",
    "Smartphone",
    "Virtual Reality Headset",
    "Augmented Reality Device",
    "Smart Speaker",
    "Wireless Router",
    "Digital Camera",
    "Microscope with Digital Output",
    "Interactive Touch Screen",
    "Digital Voice Recorder",
    "Bluetooth Headset",
    "Chromebook",
    "Gaming Console",
    "Network Switch",
    "Laser Printer",
    "Inkjet Printer",
    "Multifunction Printer",
    "Smart TV",
    "Overhead Projector",
    "Digital Signage Display",
    "Interactive Kiosk",
    "Digital Textbook Reader",
    "Smartboard",
    "E-Reader",
    "Audio Amplifier",
    "Virtual Lab Equipment",
    "Wireless Microphone",
    "Video Conferencing System",
    "Smart Lighting System",
    "Tablet Charging Cart",
    "Interactive Table",
    "Mobile Device Management System",
    "Interactive Robot",
    "Computer Numerical Control (CNC) Machine",
    "Smart Podium",
    "3D Scanner",
    "Digital Thermometer",
    "Smart Lock",
    "Document Scanner",
    "Wireless Keyboard and Mouse",
    "Digital Wall Display",
    "Video Wall Controller",
    "Air Quality Monitor",
    "Smart Thermostat",
    "Interactive Learning Device",
    "Wireless Presentation Device",
    "Digital Oscilloscope",
    "Interactive Learning Panel",
    "Robotic Arm Kit",
    "Electronic Whiteboard",
    "Digital Music Player",
    "Networked Storage Device",
    "Coding Kit for Education",
    "Smart Chair",
    "Digital Language Lab",
    "Interactive Globe",
    "RFID Attendance System",
    "Wi-Fi Extender",
    "Webcam",
    "Smart Badge System",
    "Holographic Display Device",
    "Noise Cancelling Headphones",
    "Portable Speaker",
    "Drone for Education",
    "Voice Activated Assistant",
    "Interactive Map",
    "Digital Scoreboard",
    "Motion Sensor Camera",
    "Interactive Response System",
    "Digital Microscope",
    "Virtual Field Trip Device",
    "Interactive E-Book",
    "Digital Plotter",
    "HDMI Switcher",
    "Green Screen Setup",
    "Wearable Fitness Tracker",
    "Robot Pet for Therapy",
    "Interactive Simulation Kit",
    "Solar Panel Education Kit",
    "Digital Storytelling Kit",
    "Weather Station",
    "Augmented Reality Sandbox",
    "Smart Learning Glasses",
    "Smart Wristband",
    "Interactive Timeline",
    "Digital Communication Board",
    "Interactive Puzzle",
    "Educational Drone Kit",
    "Laser Cutter",
    "Air Pressure Sensor",
    "Wireless Digital Pen",
    "Portable Interactive Projector",
    "Smart Desk",
    "Smartboard Pen",
    "Digital Piano",
    "Digital Stethoscope",
  ],
  teacherTraining: [
    "Integrating Technology in the Classroom",
    "Advanced Pedagogy for Science Teachers",
    "Inclusive Education Strategies",
    "Emotional Intelligence in Teaching",
    "Behavior Management in Schools",
    "Blended Learning Techniques",
    "Developing Critical Thinking Skills",
    "Differentiated Instruction for Diverse Learners",
    "Classroom Assessment Strategies",
    "Effective Communication for Teachers",
    "STEM Education Enhancement",
    "Culturally Responsive Teaching",
    "Advanced Classroom Management",
    "Using Data to Drive Instruction",
    "Educational Leadership and Administration",
    "Enhancing Reading and Writing Skills",
    "Teaching Strategies for Special Education",
    "Integrating Arts into the Curriculum",
    "Digital Literacy for Educators",
    "Collaborative Learning Approaches",
    "Effective Parent-Teacher Communication",
    "Building Resilience in Students",
    "Project-Based Learning Methods",
    "Flipped Classroom Approaches",
    "Social-Emotional Learning in Schools",
    "Using Gamification in Education",
    "Early Childhood Education Techniques",
    "Adapting Curriculum for Digital Learning",
    "Positive Behavior Support Systems",
    "Developing Effective Lesson Plans",
    "Inquiry-Based Science Education",
    "Advanced Literacy Strategies",
    "Growth Mindset Training for Teachers",
    "Physical Education and Health Promotion",
    "Strategies for Teaching Math Effectively",
    "Understanding Adolescent Development",
    "Teacher as a Reflective Practitioner",
    "Creating a Safe Learning Environment",
    "Engaging Students in the Learning Process",
    "Classroom Technology Integration",
    "Cognitive Learning Strategies",
    "Advanced Writing Instruction Techniques",
    "Differentiation in the Mathematics Classroom",
    "Implementing Formative Assessment Practices",
    "Building Student Motivation",
    "21st Century Skills Development",
    "Effective Questioning Techniques",
    "Multisensory Instructional Strategies",
    "Developing Digital Content for Education",
    "Maximizing Student Engagement",
    "Understanding Learning Disabilities",
    "Facilitating Group Work in the Classroom",
    "Promoting Critical Thinking Through Literature",
    "Advanced Phonics and Reading Skills",
    "Supporting English Language Learners",
    "Implementing Technology-Enhanced Learning",
    "Building a Positive Classroom Culture",
    "Handling Challenging Classroom Behavior",
    "Innovative Science Teaching Techniques",
    "Creating Interactive Learning Materials",
    "Math Problem Solving Strategies",
    "Effective Use of Learning Management Systems",
    "Developing Higher-Order Thinking Skills",
    "Incorporating Mindfulness in Education",
    "Integrating Environmental Education",
    "Technology for Language Learning",
    "Strategies for Improving Student Attendance",
    "Building a Collaborative Classroom",
    "Universal Design for Learning (UDL) Strategies",
    "Fluency Development in Reading",
    "Teaching Students with Autism",
    "Crisis Management in Schools",
    "Advanced Classroom Engagement Techniques",
    "Educating Gifted and Talented Students",
    "Exploring New Educational Technologies",
    "Creating Differentiated Learning Stations",
    "Improving Writing Skills in Elementary School",
    "Collaborative Approaches to Education",
    "Active Learning Strategies for Social Studies",
    "Using Augmented Reality in Teaching",
    "Integrating Social Media in Education",
    "Instructional Design for Online Learning",
    "Developing Emotional Literacy",
    "Strategies for Effective Homework",
    "Applying Neuroscience to Education",
    "Using AI and Data Analytics in Education",
    "Behavioral Interventions for Classroom Success",
    "Teaching Global Citizenship",
    "Building Inclusive Learning Environments",
    "Facilitating Peer Tutoring Programs",
    "Understanding Dyslexia and Intervention Techniques",
    "Differentiated Instruction Using Technology",
    "Teaching Ethics and Values in Schools",
    "Mathematics Instruction for Secondary Teachers",
    "Personalized Learning Pathways",
    "Advanced Strategies for Secondary Science Education",
    "Empowering Student Voice in the Classroom",
    "Peer Observation and Coaching",
    "Trauma-Informed Teaching Practices",
    "STEM Activities and Resources for K-12",
    "Improving Educational Outcomes with Technology",
    "Interactive Teaching Methods for History Education",
  ],
};
