export const programNames = [
  "Science",
  "Mathematics",
  "Arts",
  "Humanities",
  "Physical Education",
  "Islamic Studies",
  "Arabic Language",
  "Social Studies",
  "Information Technology",
  "Engineering",
  "Business Administration",
  "Medical Sciences",
  "Law",
  "Architecture",
  "Health Sciences",
];


export const saudiSchoolNames = [
  "King Abdullah School",
  "Al Faisal International School",
  "Saudi Academy for Science",
  "Al Noor International School",
  "Al Manar Educational Complex",
  "The Riyadh International School",
  "Jeddah Knowledge International School",
  "King Khalid Academy",
  "Dammam Model School",
  "Al Waha School",
  "The Horizon School",
  "Al Ittihad National Academy",
  "The Modern School of Riyadh",
  "Jeddah Scholars Academy",
  "Al Falah Islamic School",
  "The Arabian International School",
  "King Abdulaziz Academy",
  "Al Andalus National School",
  "Al Qamar International School",
  "Al Rawabi School",
  "The Future Leaders School",
  "Kingdom School of Education",
  "Al Ehsan Educational Complex",
  "The International Academy of Dammam",
  "Jeddah Elite School",
  "The Saudi Scholars Academy",
  "Al Hilal School",
  "King Salman Educational Complex",
  "Al Iman School for Boys",
  "Al Fursan School",
  "Dar Al Uloom International School",
  "Riyadh International Academy",
  "The Oasis School",
  "Al Jazeera International Academy",
  "The Learning Tree School",
  "King Saud School",
  "Jeddah Prep Academy",
  "Al Taif International School",
  "The Islamic Scholars School",
  "Al Bayan Educational Complex",
  "The Visionary School",
  "Al Huda International School",
  "King Abdullah Science Academy",
  "The Royal Academy of Riyadh",
  "Dammam Scholars International School",
  "Al Majd Academy",
  "The Knowledge Tree School",
  "Al Ittihad International School",
  "The Crescent School",
  "Al Ahsa International Academy",
  "The Future Vision School",
  "Al Thagir School for Girls",
  "Kingdom Scholars School",
  "Jeddah International Learning Complex",
  "Al Qasim National School",
  "Al Faris Educational Academy",
  "The Crown Academy of Saudi Arabia",
  "The Arabian Scholars School",
  "Riyadh Excellence School",
  "Al Anwar International Academy",
  "The Heritage School",
  "Al Salam International Academy",
  "King Fahd Scholars School",
  "The Knowledge Academy of Jeddah",
  "The Riyadh Scholars Complex",
  "Al Noor International Academy",
  "The Legacy School of Saudi Arabia",
  "Dammam National School for Excellence",
  "Al Hayat International School",
  "Al Wadi Academy",
  "The Future Gate School",
  "King Faisal Scholars Academy",
  "Al Muntada International School",
  "The Horizon Academy of Riyadh",
  "The Scholars Academy",
  "Al Falah School of Knowledge",
  "Jeddah Royal Academy",
];
