export const firstNames = [
  "Harshad",
  "Bhavin",
  "Amit",
  "Jignesh",
  "Ramesh",
  "Kirit",
  "Snehal",
  "Rajesh",
  "Mehul",
  "Dinesh",
  "Parth",
  "Kishore",
  "Binal",
  "Chirag",
  "Darshana",
  "Hina",
  "Kalpesh",
  "Nilesh",
  "Rupal",
  "Hetal",
  "Suresh",
  "Vishal",
  "Mahesh",
  "Tushar",
  "Priya",
  "Kavita",
  "Nisha",
  "Umesh",
  "Falguni",
  "Dharmesh",
];

export const lastNames = [
  "Patel",
  "Shah",
  "Desai",
  "Mehta",
  "Bhatt",
  "Trivedi",
  "Joshi",
  "Parekh",
  "Gandhi",
  "Vora",
  "Modi",
  "Kapadia",
  "Parikh",
  "Shroff",
  "Thakkar",
  "Dave",
  "Choksi",
  "Soni",
  "Acharya",
  "Mankad",
  "Majmudar",
  "Pandya",
  "Dholakia",
  "Gohil",
  "Rathod",
  "Solanki",
  "Jadeja",
  "Zaveri",
  "Doshi",
  "Brahmbhatt",
];

export const gujaratiHouseholdNames = [
  "Patel",
  "Desai",
  "Mehta",
  "Shah",
  "Joshi",
  "Chaudhary",
  "Parekh",
  "Thakkar",
  "Gandhi",
  "Shukla",
  "Bhatt",
  "Modi",
  "Dave",
  "Trivedi",
  "Soni",
  "Raval",
  "Suthar",
  "Patidar",
  "Vyas",
  "Makwana",
  "Nayak",
  "Parmar",
  "Solanki",
  "Prajapati",
  "Kapadia",
  "Kachhia",
  "Pandya",
  "Shroff",
  "Vora",
  "Shiroya",
  "Soni",
  "Gohil",
  "Dabhi",
  "Rathod",
  "Dhruv",
  "Gohil",
  "Kalaria",
  "Dharia",
  "Panchal",
  "Kotadia",
  "Rawal",
  "Surti",
  "Kharadi",
  "Vaghela",
  "Deshmukh",
  "Pandit",
  "Choksi",
  "Shingala",
  "Mandavia",
];

export const zipcodesInGujarat = {
  Ahmedabad: [
    380001, 380002, 380003, 380004, 380005, 380006, 380007, 380008, 380009,
    380010,
  ],
  Surat: [
    395001, 395002, 395003, 395004, 395005, 395006, 395007, 395008, 395009,
    395010,
  ],
  Vadodara: [
    390001, 390002, 390003, 390004, 390005, 390006, 390007, 390008, 390009,
    390010,
  ],
  Rajkot: [
    360001, 360002, 360003, 360004, 360005, 360006, 360007, 360008, 360009,
    360010,
  ],
  Bhavnagar: [
    364001, 364002, 364003, 364004, 364005, 364006, 364007, 364008, 364009,
    364010,
  ],
  Jamnagar: [
    361001, 361002, 361003, 361004, 361005, 361006, 361007, 361008, 361009,
    361010,
  ],
  Junagadh: [
    362001, 362002, 362003, 362004, 362005, 362006, 362007, 362008, 362009,
    362010,
  ],
  Gandhinagar: [
    382010, 382011, 382012, 382013, 382014, 382015, 382016, 382017, 382018,
    382019,
  ],
  Anand: [388001, 388002, 388003, 388004, 388005],
  Nadiad: [387001, 387002, 387003, 387004, 387005],
  Navsari: [396445, 396446, 396447, 396448, 396449, 396450],
  Vapi: [396191, 396192, 396193, 396194, 396195],
  Porbandar: [360575, 360576, 360577, 360578],
  Morbi: [363641, 363642, 363643, 363644, 363645],
  Mehsana: [384001, 384002, 384003, 384004, 384005],
  Bhuj: [370001, 370002, 370003, 370004, 370005],
};

export const streetsInGujarat = {
  Ahmedabad: [
    "C.G. Road",
    "Ashram Road",
    "Law Garden",
    "Bodakdev",
    "Satellite Road",
    "Maninagar",
    "Navrangpura",
    "Bapunagar",
  ],
  Surat: [
    "Ring Road",
    "Ghod Dod Road",
    "Dumas Road",
    "Varachha Road",
    "Adajan",
    "Athwa Lines",
    "Rander Road",
    "Udhana",
  ],
  Vadodara: [
    "Alkapuri",
    "Fatehgunj",
    "Akota",
    "Gotri Road",
    "Old Padra Road",
    "Manjalpur",
    "Waghodia Road",
    "Karelibaug",
  ],
  Rajkot: [
    "Kalavad Road",
    "Yagnik Road",
    "150 Feet Ring Road",
    "Race Course Road",
    "Saurashtra University Road",
    "Kotecha Chowk",
    "Mavdi Main Road",
    "Gondal Road",
  ],
  Bhavnagar: [
    "Waghawadi Road",
    "Barton Library Road",
    "Kalanala",
    "Ghogha Circle",
    "Takhteshwar",
    "Khodiyar Colony",
    "Vidhyanagar",
    "Chitra GIDC",
  ],
  Jamnagar: [
    "Patel Colony",
    "Indira Marg",
    "Digvijay Plot",
    "Park Colony",
    "Summair Club Road",
    "Gulabnagar",
    "Khambhalia Gate",
    "Ranjit Sagar Road",
  ],
  Junagadh: [
    "Azad Chowk",
    "Kalva Chowk",
    "Zanzarda Road",
    "Moti Baug",
    "Sardar Patel Street",
    "Joshipura",
    "Talav Gate",
    "Majevadi Gate",
  ],
  Gandhinagar: [
    "Sector 11",
    "Sector 21",
    "Sector 24",
    "Sector 7",
    "Sector 16",
    "Sector 19",
    "Sector 27",
    "Chandkheda",
  ],
  Anand: [
    "Vallabh Vidyanagar Road",
    "Amul Dairy Road",
    "Anand-Vidyanagar Road",
    "Jagnath Mahadev Road",
    "Ganesh Chowkdi",
    "Karamsad Road",
    "Sardar Gunj Road",
    "Railway Station Road",
  ],
  Nadiad: [
    "Santram Road",
    "Sardar Patel Marg",
    "Main Bazaar Road",
    "Mission Road",
    "College Road",
    "Civil Hospital Road",
    "Naroda Road",
    "Vaniya Vad",
  ],
  Navsari: [
    "Lunsikui Road",
    "Grid Road",
    "Chhapra Road",
    "Dabhel Road",
    "Rasulabad",
    "Navsari-Vijalpore Road",
    "Railway Station Road",
    "Dudhiya Talav",
  ],
  Vapi: [
    "GIDC Road",
    "Vapi Silvassa Road",
    "Gunjan",
    "Chala",
    "Imran Nagar",
    "Balitha",
    "Chanod Colony",
    "Koparli Road",
  ],
  Porbandar: [
    "M.G. Road",
    "Nehru Nagar",
    "Khijadi Plot",
    "Chowpatty Road",
    "Sudama Chowk",
    "Kutiyana Road",
    "Darbargadh",
    "Porbandar Jetty",
  ],
  Morbi: [
    "Sagar Nagar",
    "Wankaner Road",
    "Ravapar Road",
    "Morbi Bypass Road",
    "Jetpar Road",
    "Shakti Nagar",
    "Trimandir Road",
    "Amrapar Road",
  ],
  Mehsana: [
    "Modhera Road",
    "Panchot Road",
    "Kadi Road",
    "Patan Highway",
    "Radhanpur Road",
    "State Highway",
    "Nagarpalika Road",
    "Jail Road",
  ],
  Bhuj: [
    "Hospital Road",
    "Station Road",
    "Sarpat Gate",
    "Mirzapur Road",
    "Madhapar Road",
    "RTO Circle",
    "Vijay Nagar",
    "GIDC Road",
  ],
};

export const device_types = [
  "Smartphone",
  "Smart TV",
  "Laptop",
  "Tablet",
  "Smart Speaker",
  "Desktop Computer",
  "Smartwatch",
  "Game Console",
  "Smart Thermostat",
  "Smart Light",
  "Smart Fridge",
  "Smart Washing Machine",
  "Smart Doorbell",
  "Smart Lock",
  "Wearable Fitness Tracker",
  "Home Security Camera",
  "Smart Air Purifier",
  "VR Headset",
  "E-reader",
  "Smart Oven",
];

export const energySavingServices = [
  {
    type: "Smart Meter",
    description:
      "Monitors real-time electricity usage for better energy management.",
  },
  {
    type: "Energy Audit",
    description:
      "Evaluates energy consumption and provides efficiency recommendations.",
  },
  {
    type: "Solar Panels",
    description:
      "Converts sunlight into electricity, reducing dependence on the grid.",
  },
  {
    type: "LED Lighting",
    description:
      "Highly efficient lighting system that reduces energy consumption.",
  },
  {
    type: "Insulation Services",
    description:
      "Improves home insulation to reduce heating and cooling costs.",
  },
  {
    type: "Smart Thermostat",
    description: "Controls heating and cooling systems to optimize energy use.",
  },
  {
    type: "Wind Turbines",
    description: "Generates renewable energy by harnessing wind power.",
  },
  {
    type: "Rainwater Harvesting",
    description:
      "Collects and reuses rainwater to reduce water and energy costs.",
  },
  {
    type: "Solar Water Heater",
    description:
      "Heats water using solar energy, reducing electricity or gas use.",
  },
  {
    type: "Energy Efficient Appliances",
    description:
      "Uses less energy to perform the same tasks as conventional appliances.",
  },
];

export const energySavingServiceNames = [
  "EcoPower Solutions",
  "Green Energy Systems",
  "Solar Tech Innovators",
  "EcoSmart Utilities",
  "Energy Efficiency Experts",
  "Sustainability Hub",
  "Green Grid Solutions",
  "SunPower Innovations",
  "EcoLight Systems",
  "SmartEnergy Solutions",
  "Future Energy Technologies",
  "Renewable Energy Partners",
  "EcoThermal Systems",
  "Energy Savvy Solutions",
  "GreenGuard Energy",
];

export const eligibilityCriteriaOptions = [
  "Households with monthly energy consumption above 500 kWh",
  "Eligibility for government energy subsidy programs",
  "Residents of rural areas with access to solar installations",
  "Income level below ₹50,000 per month to qualify for subsidies",
  "Households with energy efficiency audits within the last year",
  "Owners of properties above 1000 square feet",
  "Eligibility for renewable energy tax incentives",
  "Households registered with local energy-saving initiatives",
  "Only applicable to new constructions with green certifications",
  "Must have a smart meter installed",
];

export const safetySecurityServiceNames = [
  "24/7 Home Surveillance",
  "Fire Safety Systems",
  "Smart Door Lock System",
  "Personal Emergency Alert Service",
  "Neighborhood Watch Program",
  "Vehicle Tracking Service",
  "Security Camera Installation",
  "Intruder Detection System",
  "Remote Security Monitoring",
  "Emergency Medical Response",
];

export const safetySecurityServiceDescriptions = [
  "Provides round-the-clock monitoring of your home using advanced security cameras.",
  "Comprehensive fire safety system for homes, including alarms and sprinklers.",
  "Advanced smart lock system to ensure the safety of your property.",
  "Emergency alert service that connects users to nearby responders in case of danger.",
  "Community-led security initiative to keep neighborhoods safe.",
  "Real-time tracking and monitoring of personal vehicles for added security.",
  "Installation of high-quality security cameras to monitor all entry points.",
  "Intruder detection system with real-time alerts to your mobile device.",
  "Remote security monitoring services managed by professionals.",
  "Immediate medical response system for elderly or at-risk individuals.",
];

export const safetySecurityEligibilityCriteria = [
  "Residents in high-crime areas are prioritized.",
  "Homes with previous safety violations are eligible for discounts.",
  "Only available to properties with smart devices installed.",
  "Eligibility based on neighborhood risk assessment score.",
  "Homeowners with young children or elderly family members are prioritized.",
  "Must have a home insurance policy for installation eligibility.",
  "Available for commercial buildings with more than 5,000 square feet.",
  "Requires a smart home hub for system integration.",
  "Discounted for households with an annual income below ₹5 lakhs.",
  "Prioritized for properties with a history of medical emergencies.",
];


export const rewardsProgramNames = [
  "Green Energy Saver Rewards",
  "Safe Home Initiative Points",
  "Community Health Bonus Program",
  "Smart Home User Loyalty Program",
  "Security System Upgrade Rewards",
  "Energy Efficiency Incentive Program",
  "Neighborhood Watch Participation Bonus",
  "Sustainable Living Discount Program",
  "Homeowner Insurance Cashback",
  "Family Safety and Security Rewards",
];

export const rewardsProgramDescriptions = [
  "Earn points for reducing household energy consumption.",
  "Rewards program for maintaining safety and security standards in your home.",
  "Bonus points for taking proactive health and safety measures.",
  "Loyalty points for continuous use of smart home devices.",
  "Upgrade your security system and earn points toward future discounts.",
  "Incentives for installing energy-efficient appliances and devices.",
  "Earn points by participating in community safety and watch programs.",
  "Get discounts for adopting sustainable and eco-friendly home practices.",
  "Cashback rewards for having active home insurance policies.",
  "Points for integrating family safety features in your household.",
];

export const pointsCriteriaOptions = [
  "Earn 1 point for every ₹100 spent on energy-saving products.",
  "Earn 5 points for every safety device installed in the household.",
  "Earn 10 points for every home health checkup completed.",
  "Loyalty points increase by 10% for every year of continued use.",
  "5 points for every security upgrade performed in the household.",
  "Earn 2 points for every ₹50 saved on energy bills.",
  "Earn 3 points for attending community safety meetings.",
  "Points are awarded for reducing your home’s carbon footprint.",
  "Receive 10 points for keeping your insurance policy active for a year.",
  "Earn 5 points for installing smart safety devices in your home.",
];

export const marketplaceOperatorNames = [
  "GreenTech Solutions",
  "SafeGuard Innovations",
  "EcoEnergy Systems",
  "HomeSecure Services",
  "Sustainable Future Corp",
  "BrightHome Technologies",
  "EnergyWise Networks",
  "SecureLiving Platforms",
  "SmartGrid Solutions",
  "EcoSaver Enterprises",
];

export const marketplaceOperatorDescriptions = [
  "Leading provider of eco-friendly energy solutions for homes.",
  "Innovative safety solutions for residential communities.",
  "Pioneers in sustainable energy technologies for households.",
  "Comprehensive security services for home safety and monitoring.",
  "Promoting a sustainable future through smart home technologies.",
  "Cutting-edge smart home services for energy conservation.",
  "Network of energy-saving solutions for residential areas.",
  "Providing secure living through advanced home monitoring.",
  "Innovative platform for smart grid energy management.",
  "Eco-friendly services promoting energy efficiency in homes.",
];

export const subsidyProviderNames = [
  "Gujarat Renewable Energy Development Agency",
  "Clean Energy Financial Corp",
  "Green Subsidy Foundation",
  "Sustainable Energy Assistance",
  "Government of Gujarat Energy Grants",
  "EcoFund Solutions",
  "Energy Efficiency Support Trust",
  "Solar Energy Subsidy Program",
  "Renewable Resource Fund",
  "Sustainability Grants Initiative",
];

export const subsidyProviderDescriptions = [
  "Providing financial support for renewable energy projects.",
  "Offering grants and subsidies for energy-saving technologies.",
  "Supporting sustainable energy initiatives through funding.",
  "Facilitating financial aid for clean energy adoption.",
  "Government-backed subsidies for energy efficiency programs.",
  "Promoting eco-friendly solutions through financial grants.",
  "Financial assistance for energy efficiency and conservation.",
  "Subsidizing solar power adoption across communities.",
  "Funding programs for renewable energy installations.",
  "Driving sustainability through grants and incentives.",
];

export const insuranceCompanyNames = [
  "SafeGuard Insurance Co.",
  "Bharat General Insurance",
  "SecureFuture Insurance",
  "EcoShield Insurance Group",
  "GreenProtect Insurance",
  "EnergyCare Insurance Solutions",
  "Global Security Assurance",
  "SafeHouse Property Insurance",
  "Sustainable Risk Coverage",
  "Gujarat Risk Protection",
];

export const insuranceCompanyDescriptions = [
  "Providing comprehensive property and energy coverage.",
  "Ensuring risk protection for sustainable energy solutions.",
  "Offering tailored insurance solutions for households and businesses.",
  "Coverage plans designed for energy-efficient and secure homes.",
  "Specialized insurance for energy-saving technologies and systems.",
  "Comprehensive protection for property and security services.",
  "Providing risk coverage for clean energy and property.",
  "Affordable insurance plans for green technology adoption.",
  "Ensuring security and sustainability with comprehensive policies.",
  "Protecting your assets with tailored coverage solutions.",
];

export const laborUnionNames = [
  "Gujarat Mazdoor Sabha",
  "Akhil Gujarat Kamdar Mandal",
  "Bharat Workers Federation",
  "Saurashtra Labor Union",
  "Gujarat Industrial Workers Association",
  "Khedut Kamdar Sangh",
  "Western Gujarat Trade Union",
  "Akhil Bharat Mazdoor Sangh",
  "Sustainable Workers Collective",
  "Gujarat Labor Rights Council",
];

export const laborUnionDescriptions = [
  "Advocating for workers' rights and fair wages in Gujarat.",
  "Ensuring safety and fair working conditions for industrial workers.",
  "Promoting the rights and welfare of workers across industries.",
  "Dedicated to protecting the interests of laborers and tradespeople.",
  "Empowering workers through collective bargaining and representation.",
  "Providing legal and social support to the labor force.",
  "Fostering better working conditions for sustainable employment.",
  "Representing workers in negotiations for fair pay and benefits.",
  "Committed to labor rights and equitable treatment of all workers.",
  "Championing the cause of safe and secure workplaces for all.",
];
