export const metric_name = [
  "Literacy Rate Improvement",
  "Student Attendance Rate",
  "STEM Subject Enrollment",
  "Teacher Training Completion",
  "Digital Learning Tool Adoption",
  "Early Childhood Education Access",
  "Research Paper Publications",
  "Inclusion of Special Needs Students",
  "Dropout Rate Reduction",
  "Scholarship Distribution Rate",
  "Vocational Training Participation",
  "Language Proficiency Improvement",
  "Infrastructure Development Rate",
  "Parental Involvement Increase",
  "Health and Nutrition Awareness",
  "Physical Fitness Participation",
  "Environmental Awareness Programs",
  "Special Education Service Expansion",
  "Professional Development Hours",
  "Classroom Technology Integration",
  "Arts and Cultural Event Participation",
  "Global Citizenship Understanding",
  "Critical Thinking Skill Development",
  "Entrepreneurship Course Enrollment",
  "Sexual Health Awareness Programs",
  "Anti-Bullying Initiative Effectiveness",
  "Financial Literacy Program Reach",
  "Inclusive Classroom Environment",
  "Reading Program Effectiveness",
  "School Safety Audit Compliance",
  "Social and Emotional Learning",
  "STEM Competition Participation",
  "Student Leadership Activity",
  "Peer Tutoring Program Impact",
  "Digital Literacy Achievement",
  "Distance Learning Engagement",
  "Lifelong Learning Promotion",
  "Career Counseling Impact",
  "Reduced Class Sizes",
  "Hybrid Learning Implementation",
];
