export const vision2030 = [
  {
    description:
      "A strategy focused on improving educational standards across all levels.",
    primaryGoals: "Increase literacy, Enhance STEM education",
    keyChallenges: "Low teacher engagement",
    stakeholders: "Ministry of Education, NGOs",
    geographicScope: "National",
    riskFactors: "Budget constraints, Low participation",
    mitigationPlans: "Increase funding, Awareness programs",
    performanceMetrics: "Literacy Rate, STEM Performance",
  },
  {
    description:
      "A project aimed at integrating digital learning tools into classrooms nationwide.",
    primaryGoals: "Improve digital literacy, Provide digital tools",
    keyChallenges: "Lack of digital infrastructure",
    stakeholders: "Tech Companies, Schools",
    geographicScope: "National",
    riskFactors: "High initial costs, Digital divide",
    mitigationPlans: "Public-private partnerships, Subsidies",
    performanceMetrics: "Digital Literacy, Device Distribution",
  },
  {
    description:
      "An initiative to provide free and quality education to underprivileged children.",
    primaryGoals: "Increase access to education, Reduce inequality",
    keyChallenges: "High dropout rates, Low funding",
    stakeholders: "Government, Philanthropists",
    geographicScope: "Urban and Rural",
    riskFactors: "Community resistance, Funding challenges",
    mitigationPlans: "Community engagement, Additional grants",
    performanceMetrics: "Enrollment Rates, Graduation Rates",
  },
  {
    description:
      "A comprehensive plan to enhance STEM education in high schools through specialized training.",
    primaryGoals: "Increase STEM graduates, Improve STEM teaching",
    keyChallenges: "Shortage of qualified teachers",
    stakeholders: "Universities, Educational Boards",
    geographicScope: "National",
    riskFactors: "Teacher retention, Resource availability",
    mitigationPlans: "Incentive programs, Continued education",
    performanceMetrics: "STEM Enrollment, Teacher Training Levels",
  },
  {
    description:
      "A strategy to strengthen vocational training programs for students not pursuing higher education.",
    primaryGoals: "Expand vocational training, Improve employability",
    keyChallenges: "Low enrollment in vocational courses",
    stakeholders: "Local Industries, Training Institutes",
    geographicScope: "Regional",
    riskFactors: "Perception of vocational training, Curriculum relevance",
    mitigationPlans: "Awareness campaigns, Curriculum updates",
    performanceMetrics: "Vocational Training Enrollment, Employment Rates",
  },
  {
    description:
      "A campaign to promote inclusive education for children with special needs.",
    primaryGoals: "Ensure inclusive education, Train specialized educators",
    keyChallenges: "Lack of resources, Stigma",
    stakeholders: "Special Education Centers, NGOs",
    geographicScope: "National",
    riskFactors: "Low awareness, High costs",
    mitigationPlans: "Advocacy programs, Government funding",
    performanceMetrics: "Inclusion Rates, Educator Training",
  },
  {
    description:
      "A project to integrate environmental education into the school curriculum.",
    primaryGoals: "Promote sustainability, Environmental awareness",
    keyChallenges: "Curriculum rigidity, Lack of trained teachers",
    stakeholders: "Environmental NGOs, Schools",
    geographicScope: "National",
    riskFactors: "Resistance to change, Lack of resources",
    mitigationPlans: "Pilot programs, Teacher training",
    performanceMetrics: "Curriculum Integration, Student Awareness Levels",
  },
  {
    description:
      "A strategy to create a digital repository for all educational resources.",
    primaryGoals: "Enhance access to resources, Improve learning outcomes",
    keyChallenges: "Technical challenges, Resource availability",
    stakeholders: "Ministry of Education, Libraries",
    geographicScope: "National",
    riskFactors: "Data privacy, Digital access",
    mitigationPlans: "Data protection policies, Infrastructure upgrades",
    performanceMetrics: "Resource Usage, Access Rates",
  },
  {
    description:
      "A plan to improve early childhood education through community-based programs.",
    primaryGoals: "Increase early education enrollment, Engage communities",
    keyChallenges: "Parental resistance, Limited facilities",
    stakeholders: "Local Communities, Government",
    geographicScope: "Rural",
    riskFactors: "Cultural barriers, Resource allocation",
    mitigationPlans: "Community workshops, Mobile education units",
    performanceMetrics: "Enrollment Rates, Program Reach",
  },
  {
    description:
      "A project to implement an AI-based personalized learning system in schools.",
    primaryGoals: "Enhance personalized learning, Use AI in education",
    keyChallenges: "Technological adoption, Privacy concerns",
    stakeholders: "Tech Companies, Schools",
    geographicScope: "Urban",
    riskFactors: "Data misuse, High costs",
    mitigationPlans: "Clear guidelines, Government funding",
    performanceMetrics: "Student Performance, System Utilization",
  },
  {
    description:
      "An initiative to build partnerships with international universities for research and development.",
    primaryGoals: "Enhance research, International collaboration",
    keyChallenges: "Bureaucratic hurdles, Lack of awareness",
    stakeholders: "Universities, Research Centers",
    geographicScope: "Global",
    riskFactors: "Low interest, Regulatory issues",
    mitigationPlans: "Policy reforms, Awareness programs",
    performanceMetrics: "Partnership Agreements, Research Output",
  },
  {
    description:
      "A comprehensive plan to provide digital classrooms and virtual labs in underserved areas.",
    primaryGoals: "Reduce education inequality, Enhance digital learning",
    keyChallenges: "Infrastructure gaps, Low digital literacy",
    stakeholders: "Telecom Companies, Schools",
    geographicScope: "Rural",
    riskFactors: "Technical issues, High costs",
    mitigationPlans: "Subsidized infrastructure, Training programs",
    performanceMetrics: "Digital Literacy Rates, Classroom Usage",
  },
  {
    description:
      "A strategy to launch an educational TV channel to provide remote learning.",
    primaryGoals: "Expand remote learning, Enhance educational reach",
    keyChallenges: "Content creation, Audience engagement",
    stakeholders: "Media Houses, Schools",
    geographicScope: "National",
    riskFactors: "Content relevance, Low viewership",
    mitigationPlans: "Content partnerships, Interactive sessions",
    performanceMetrics: "Channel Ratings, Learning Outcomes",
  },
  {
    description:
      "A project to integrate coding and programming into the school curriculum from an early age.",
    primaryGoals: "Enhance computational skills, Promote coding education",
    keyChallenges: "Lack of trained teachers, Curriculum overload",
    stakeholders: "Tech Companies, Schools",
    geographicScope: "National",
    riskFactors: "Resistance to change, Resource availability",
    mitigationPlans: "Teacher training, Curriculum updates",
    performanceMetrics: "Coding Proficiency, Enrollment in Coding Classes",
  },
  {
    description:
      "A plan to enhance teacher engagement through continuous professional development programs.",
    primaryGoals: "Improve teaching quality, Increase teacher retention",
    keyChallenges: "Lack of incentives, Workload issues",
    stakeholders: "Teacher Unions, Schools",
    geographicScope: "National",
    riskFactors: "Low participation, High costs",
    mitigationPlans: "Incentive programs, Flexible schedules",
    performanceMetrics: "Training Completion Rates, Teacher Satisfaction",
  },
  {
    description:
      "A campaign to build career counseling centers in schools to guide students.",
    primaryGoals: "Provide career guidance, Reduce career confusion",
    keyChallenges: "Lack of trained counselors",
    stakeholders: "Career Experts, Schools",
    geographicScope: "National",
    riskFactors: "Low uptake, High costs",
    mitigationPlans: "Online counseling, Government subsidies",
    performanceMetrics: "Counseling Sessions, Student Satisfaction",
  },
  {
    description:
      "A strategy to establish research centers of excellence in key universities.",
    primaryGoals: "Enhance research quality, Promote innovation",
    keyChallenges: "Funding limitations, Talent retention",
    stakeholders: "Universities, Research Organizations",
    geographicScope: "National",
    riskFactors: "Low research output, High turnover",
    mitigationPlans: "Research grants, Retention programs",
    performanceMetrics: "Research Publications, Patent Filings",
  },
  {
    description:
      "A project to introduce financial literacy as a mandatory subject in high schools.",
    primaryGoals: "Improve financial literacy, Prepare students for adulthood",
    keyChallenges: "Curriculum integration, Teacher training",
    stakeholders: "Financial Institutions, Schools",
    geographicScope: "National",
    riskFactors: "Low interest, Curriculum overload",
    mitigationPlans: "Training programs, Interactive learning",
    performanceMetrics: "Financial Literacy Scores, Course Enrollment",
  },
  {
    description:
      "An initiative to launch a nationwide competition to promote innovation among students.",
    primaryGoals: "Foster creativity, Encourage innovation",
    keyChallenges: "Logistics, Low participation",
    stakeholders: "Innovation Hubs, Schools",
    geographicScope: "National",
    riskFactors: "Low engagement, High costs",
    mitigationPlans: "Partnerships, Incentive programs",
    performanceMetrics: "Participation Rates, Innovation Projects",
  },
  {
    description:
      "A strategy to introduce mindfulness and emotional intelligence training in schools.",
    primaryGoals: "Improve student well-being, Promote emotional health",
    keyChallenges: "Lack of trained educators, Curriculum overload",
    stakeholders: "Mental Health Experts, Schools",
    geographicScope: "National",
    riskFactors: "Low engagement, High costs",
    mitigationPlans: "Teacher training, Awareness programs",
    performanceMetrics: "Student Well-being Scores, Participation Rates",
  },
  {
    description:
      "A strategy to develop smart classrooms equipped with the latest technology.",
    primaryGoals:
      "Modernize education infrastructure, Improve digital learning",
    keyChallenges: "High cost of technology, Resistance to change",
    stakeholders: "Tech Companies, Schools, Local Governments",
    geographicScope: "Urban and Semi-Urban",
    riskFactors: "High implementation cost, Digital divide",
    mitigationPlans: "Public-private partnerships, Funding from tech companies",
    performanceMetrics:
      "Smart Classroom Adoption Rate, Student Engagement Levels",
  },
  {
    description:
      "An initiative to provide nutrition programs to students in public schools.",
    primaryGoals: "Improve student health, Enhance learning ability",
    keyChallenges: "Funding, Logistics",
    stakeholders: "Health Ministry, Schools, NGOs",
    geographicScope: "National",
    riskFactors: "High operational cost, Supply chain issues",
    mitigationPlans: "Partnership with local farmers, Community involvement",
    performanceMetrics:
      "Nutrition Program Participation, Student Health Improvement",
  },
  {
    description:
      "A project aimed at incorporating entrepreneurship training in high school curriculum.",
    primaryGoals: "Encourage entrepreneurship, Foster innovation",
    keyChallenges: "Lack of trained educators, Curriculum overload",
    stakeholders: "Business Schools, High Schools, Entrepreneurs",
    geographicScope: "National",
    riskFactors: "Resistance from educators, High training costs",
    mitigationPlans: "Workshops, Industry partnerships",
    performanceMetrics:
      "Entrepreneurship Program Enrollment, New Business Startups",
  },
  {
    description:
      "A strategy to implement free healthcare checks in schools to ensure student well-being.",
    primaryGoals: "Enhance student health, Prevent health issues",
    keyChallenges: "Lack of healthcare professionals, Funding issues",
    stakeholders: "Health Ministry, Schools, Local Clinics",
    geographicScope: "National",
    riskFactors: "Operational challenges, Parental resistance",
    mitigationPlans: "Mobile healthcare units, Subsidized services",
    performanceMetrics: "Health Check Participation, Issue Detection Rate",
  },
  {
    description:
      "A comprehensive plan to offer language learning programs across schools.",
    primaryGoals: "Enhance language skills, Promote cultural understanding",
    keyChallenges: "Lack of qualified teachers, Resource constraints",
    stakeholders: "Linguistic Institutes, Schools",
    geographicScope: "National",
    riskFactors: "Low student interest, Curriculum rigidity",
    mitigationPlans: "Interactive programs, Exchange programs",
    performanceMetrics: "Language Proficiency, Program Enrollment",
  },
  {
    description:
      "A project to establish libraries and digital resource centers in remote areas.",
    primaryGoals: "Improve access to education, Promote lifelong learning",
    keyChallenges: "Infrastructure gaps, Lack of digital literacy",
    stakeholders: "Libraries, Community Centers, NGOs",
    geographicScope: "Rural",
    riskFactors: "Low utilization, High setup cost",
    mitigationPlans: "Mobile libraries, Community engagement",
    performanceMetrics: "Library Memberships, Resource Utilization",
  },
  {
    description:
      "A campaign to create awareness about environmental sustainability in schools.",
    primaryGoals: "Promote environmental education, Encourage sustainability",
    keyChallenges: "Lack of awareness, Limited resources",
    stakeholders: "Environmental NGOs, Schools",
    geographicScope: "National",
    riskFactors: "Low participation, High program costs",
    mitigationPlans: "Sponsorships, Volunteer programs",
    performanceMetrics: "Student Engagement, Awareness Level",
  },
  {
    description:
      "A strategy to integrate sports education in school curriculums to foster physical fitness.",
    primaryGoals: "Enhance physical health, Promote team spirit",
    keyChallenges: "Lack of infrastructure, Insufficient funding",
    stakeholders: "Sports Academies, Schools, Health Ministry",
    geographicScope: "National",
    riskFactors: "High infrastructure costs, Low participation",
    mitigationPlans: "Grants for sports facilities, Community sports programs",
    performanceMetrics: "Sports Program Enrollment, Student Health Scores",
  },
  {
    description:
      "An initiative to implement AI-driven personalized tutoring systems in schools.",
    primaryGoals: "Improve learning outcomes, Enhance personalized learning",
    keyChallenges: "Data privacy concerns, Technological adoption",
    stakeholders: "EdTech Companies, Schools",
    geographicScope: "Urban",
    riskFactors: "High development cost, Resistance from educators",
    mitigationPlans: "Pilot projects, Data protection policies",
    performanceMetrics: "Student Learning Outcomes, System Usage Rates",
  },
  {
    description:
      "A plan to develop community-based education models in rural areas.",
    primaryGoals: "Improve access to education, Engage local communities",
    keyChallenges: "Cultural barriers, Lack of infrastructure",
    stakeholders: "Local Leaders, Schools, NGOs",
    geographicScope: "Rural",
    riskFactors: "Community resistance, Low funding",
    mitigationPlans: "Community engagement, Alternative education models",
    performanceMetrics: "Community Participation, Student Enrollment",
  },
  {
    description:
      "A project to provide scholarships for students pursuing STEM fields.",
    primaryGoals: "Promote STEM education, Reduce financial barriers",
    keyChallenges: "Funding limitations, Awareness",
    stakeholders: "Scholarship Boards, Universities",
    geographicScope: "National",
    riskFactors: "Low application rates, Misuse of funds",
    mitigationPlans: "Awareness campaigns, Transparent selection process",
    performanceMetrics: "Scholarship Applications, STEM Graduates",
  },
  {
    description:
      "An initiative to promote lifelong learning through adult education programs.",
    primaryGoals: "Improve literacy rates, Promote continuous learning",
    keyChallenges: "Low enrollment, Cultural resistance",
    stakeholders: "Adult Education Centers, NGOs",
    geographicScope: "National",
    riskFactors: "Funding challenges, Low retention",
    mitigationPlans: "Incentives for learners, Community awareness",
    performanceMetrics: "Enrollment Rates, Literacy Improvement",
  },
  {
    description:
      "A campaign to foster innovation through science and technology fairs in schools.",
    primaryGoals: "Encourage scientific thinking, Promote innovation",
    keyChallenges: "Low student interest, Funding",
    stakeholders: "Schools, Science Clubs, Tech Companies",
    geographicScope: "National",
    riskFactors: "Low participation, High costs",
    mitigationPlans: "Partnerships, Incentives for winners",
    performanceMetrics: "Participation Rates, Innovation Projects",
  },
  {
    description:
      "A comprehensive strategy to improve teacher-student ratio in public schools.",
    primaryGoals: "Enhance teaching quality, Improve learning outcomes",
    keyChallenges: "Lack of qualified teachers, High student enrollment",
    stakeholders: "Ministry of Education, Schools",
    geographicScope: "National",
    riskFactors: "High recruitment cost, Teacher attrition",
    mitigationPlans: "Teacher training programs, Retention incentives",
    performanceMetrics: "Teacher-Student Ratio, Student Performance",
  },
  {
    description:
      "A plan to promote arts education in schools to enhance creativity.",
    primaryGoals: "Promote arts education, Foster creativity",
    keyChallenges: "Low student interest, Lack of resources",
    stakeholders: "Arts Councils, Schools",
    geographicScope: "National",
    riskFactors: "Low participation, Curriculum overload",
    mitigationPlans: "Art competitions, Community involvement",
    performanceMetrics: "Arts Program Enrollment, Student Creativity",
  },
  {
    description:
      "An initiative to provide free Wi-Fi in schools to promote digital learning.",
    primaryGoals: "Enhance digital learning, Improve internet access",
    keyChallenges: "High infrastructure costs, Security concerns",
    stakeholders: "Telecom Companies, Schools",
    geographicScope: "Urban and Rural",
    riskFactors: "Network reliability, Data privacy",
    mitigationPlans: "Secure network setup, Maintenance contracts",
    performanceMetrics: "Internet Usage, Student Engagement",
  },
  {
    description:
      "A project to create a national repository of open educational resources (OER).",
    primaryGoals: "Enhance resource accessibility, Promote knowledge sharing",
    keyChallenges: "Content quality, Intellectual property",
    stakeholders: "Universities, Educational Institutions",
    geographicScope: "National",
    riskFactors: "Low content submission, Copyright issues",
    mitigationPlans: "Incentives for content creators, Awareness programs",
    performanceMetrics: "OER Usage, Content Upload Rates",
  },
  {
    description:
      "A strategy to develop resilience-building programs for students.",
    primaryGoals: "Enhance mental health, Promote resilience",
    keyChallenges: "Lack of trained professionals, Low awareness",
    stakeholders: "Mental Health Experts, Schools",
    geographicScope: "National",
    riskFactors: "Low participation, High costs",
    mitigationPlans: "Training for teachers, Awareness campaigns",
    performanceMetrics: "Program Participation, Student Resilience Scores",
  },
  {
    description: "A strategy to improve digital skills among teachers.",
    primaryGoals: "Enhance teaching quality, Integrate digital tools",
    keyChallenges: "Resistance to technology, Lack of training",
    stakeholders: "Schools, Teacher Training Institutes",
    geographicScope: "National",
    riskFactors: "Low adoption rates, High training costs",
    mitigationPlans: "Ongoing support, Incentive programs",
    performanceMetrics: "Teacher Digital Skills, Student Feedback",
  },
  {
    description:
      "A project to establish youth mentorship programs to reduce dropout rates.",
    primaryGoals: "Reduce dropout rates, Improve academic performance",
    keyChallenges: "Lack of mentors, Low engagement",
    stakeholders: "Alumni Networks, NGOs, Schools",
    geographicScope: "Urban and Rural",
    riskFactors: "Low mentor availability, High dropout rates",
    mitigationPlans: "Incentives for mentors, Regular monitoring",
    performanceMetrics: "Dropout Rate Reduction, Student Engagement",
  },
];
